/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewIndexRouteImport } from './routes/new/index'
import { Route as IdeasIndexRouteImport } from './routes/ideas/index'
import { Route as IdeasIdeaIdIndexRouteImport } from './routes/ideas/$ideaId/index'
import { Route as IdeasIdeaIdEditIndexRouteImport } from './routes/ideas/$ideaId/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewIndexRoute = NewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdIndexRoute = IdeasIdeaIdIndexRouteImport.update({
  id: '/ideas/$ideaId/',
  path: '/ideas/$ideaId/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdEditIndexRoute = IdeasIdeaIdEditIndexRouteImport.update({
  id: '/ideas/$ideaId/edit/',
  path: '/ideas/$ideaId/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasIndexRoute
  '/new': typeof NewIndexRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdIndexRoute
  '/ideas/$ideaId/edit': typeof IdeasIdeaIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasIndexRoute
  '/new': typeof NewIndexRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdIndexRoute
  '/ideas/$ideaId/edit': typeof IdeasIdeaIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas/': typeof IdeasIndexRoute
  '/new/': typeof NewIndexRoute
  '/ideas/$ideaId/': typeof IdeasIdeaIdIndexRoute
  '/ideas/$ideaId/edit/': typeof IdeasIdeaIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ideas' | '/new' | '/ideas/$ideaId' | '/ideas/$ideaId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ideas' | '/new' | '/ideas/$ideaId' | '/ideas/$ideaId/edit'
  id:
    | '__root__'
    | '/'
    | '/ideas/'
    | '/new/'
    | '/ideas/$ideaId/'
    | '/ideas/$ideaId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
  NewIndexRoute: typeof NewIndexRoute
  IdeasIdeaIdIndexRoute: typeof IdeasIdeaIdIndexRoute
  IdeasIdeaIdEditIndexRoute: typeof IdeasIdeaIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/': {
      id: '/new/'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId/': {
      id: '/ideas/$ideaId/'
      path: '/ideas/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId/edit/': {
      id: '/ideas/$ideaId/edit/'
      path: '/ideas/$ideaId/edit'
      fullPath: '/ideas/$ideaId/edit'
      preLoaderRoute: typeof IdeasIdeaIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasIndexRoute: IdeasIndexRoute,
  NewIndexRoute: NewIndexRoute,
  IdeasIdeaIdIndexRoute: IdeasIdeaIdIndexRoute,
  IdeasIdeaIdEditIndexRoute: IdeasIdeaIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
